name:          Руководство по написанию кода frontendanon
description:   Стандарты для разработки гибкого, надежного и поддерживаемого кода на Pug(Jade) и Stylus.
url:           http://mdo.github.com/code-guide

markdown:      rdiscount
permalink:     pretty
rouge:      true
